/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import accesoADatos.InscripcionData;
import accesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Materia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andres
 */
public class AlumnoPorMateria extends javax.swing.JInternalFrame {

    MateriaData materiaData = new MateriaData();
    DefaultTableModel modelo = new DefaultTableModel();
    InscripcionData inscripcionData = new InscripcionData();

    /**
     * Creates new form AlumnoPorMateria
     */
    public AlumnoPorMateria() {
        initComponents();
        setSize(586, 524);
        cargarCombo();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cBlistadoMaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tBListaalumnos = new javax.swing.JTable();
        bSalir = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(39, 60, 117));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado de Alumnos por Materia");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 500, 24);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(40, 40, 500, 10);

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione una Materia: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 90, 190, 18);

        cBlistadoMaterias.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        cBlistadoMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBlistadoMateriasActionPerformed(evt);
            }
        });
        jPanel1.add(cBlistadoMaterias);
        cBlistadoMaterias.setBounds(280, 90, 260, 25);

        tBListaalumnos.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        tBListaalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tBListaalumnos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 150, 500, 260);

        bSalir.setBackground(new java.awt.Color(12, 43, 135));
        bSalir.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bSalir.setForeground(new java.awt.Color(255, 255, 255));
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel1.add(bSalir);
        bSalir.setBounds(460, 440, 72, 28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBlistadoMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBlistadoMateriasActionPerformed
        Materia materia = (Materia) cBlistadoMaterias.getSelectedItem();
        List<Alumno> listaAlumno = new ArrayList<>();
        listaAlumno = inscripcionData.obtenerAlumnoPorMateria(materia.getIdMateria());
        modelo.setRowCount(0);
        for (Alumno alumno : listaAlumno) {
            modelo.addRow(new Object[]{alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(), alumno.getNombre()});
            
        }

    }//GEN-LAST:event_cBlistadoMateriasActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<Materia> cBlistadoMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tBListaalumnos;
    // End of variables declaration//GEN-END:variables
private void cargarCombo() {
        List<Materia> listaMaterias = new ArrayList<>();
        listaMaterias = materiaData.listarMaterias();
        if (listaMaterias != null) {
            for (Materia materia : listaMaterias) {
                cBlistadoMaterias.addItem(materia);                
            }
        }
    }

    private void armarCabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        tBListaalumnos.setModel(modelo);
    }
}
