package vistas;

import accesoADatos.AlumnoData;
import entidades.Alumno;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andres
 */
public class AlumnosPorApellidoView extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    AlumnoData alumnoData = new AlumnoData();

    public AlumnosPorApellidoView() {
        initComponents();
        //setSize(700, 600);
        setSize(586, 524);
        cabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEncontrados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbPanelApellido = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbPanelNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbPanelDni = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbPanelId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(39, 60, 117));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Digite el Apellido:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 70, 200, 30);

        tfApellido.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfApellidoPropertyChange(evt);
            }
        });
        tfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfApellidoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(tfApellido);
        tfApellido.setBounds(260, 70, 280, 30);

        tbEncontrados.setBackground(new java.awt.Color(204, 255, 255));
        tbEncontrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEncontrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEncontradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEncontrados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 350, 340);

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Buscar Alumnos Activos por Apellido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 520, 24);

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumno_1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");

        lbPanelApellido.setFont(new java.awt.Font("Roboto Medium", 1, 15)); // NOI18N
        lbPanelApellido.setForeground(new java.awt.Color(0, 204, 255));
        lbPanelApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPanelApellido.setText("*********");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre: ");

        lbPanelNombre.setFont(new java.awt.Font("Roboto Medium", 1, 15)); // NOI18N
        lbPanelNombre.setForeground(new java.awt.Color(0, 204, 255));
        lbPanelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPanelNombre.setText("*********");

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dni:");

        lbPanelDni.setFont(new java.awt.Font("Roboto Medium", 1, 15)); // NOI18N
        lbPanelDni.setForeground(new java.awt.Color(0, 204, 255));
        lbPanelDni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPanelDni.setText("*********");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");

        lbPanelId.setFont(new java.awt.Font("Roboto Medium", 1, 15)); // NOI18N
        lbPanelId.setForeground(new java.awt.Color(0, 204, 255));
        lbPanelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPanelId.setText("*********");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(lbPanelApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPanelDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPanelNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lbPanelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lbPanelId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPanelApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(lbPanelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lbPanelDni)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(380, 120, 160, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoKeyTyped
        AccesoService.Service.esLetra(evt);
    }//GEN-LAST:event_tfApellidoKeyTyped

    private void tfApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoKeyReleased
        cleanPanel();
// busqueda por cada letra tecleada...
        String apellido = tfApellido.getText();
        List<Alumno> alumnoEncontrado = alumnoData.listaAlumnosPorApellido(apellido);

        // Limpiar el modelo de la tabla antes de agregar nuevos datos      
        modelo.setRowCount(0);

        if (alumnoEncontrado != null) {
            for (Alumno alumno : alumnoEncontrado) {
                modelo.addRow(new Object[]{alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(), alumno.getNombre()});
            }
        }
    }//GEN-LAST:event_tfApellidoKeyReleased

    private void tfApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoKeyPressed
//
    }//GEN-LAST:event_tfApellidoKeyPressed

    private void tbEncontradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEncontradosMouseClicked
        int fila = tbEncontrados.getSelectedRow();
        int idAlumno = (int) tbEncontrados.getValueAt(fila, 0);
        Alumno alumno = alumnoData.buscarAlumno(idAlumno);
        if (alumno != null && alumno.isActivo()) {
            lbPanelId.setText(String.valueOf(alumno.getIdAlumno()));
            lbPanelApellido.setText(alumno.getApellido());
            lbPanelNombre.setText(alumno.getNombre());
            lbPanelDni.setText(String.valueOf(alumno.getDni()));
        }
    }//GEN-LAST:event_tbEncontradosMouseClicked

    private void tfApellidoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfApellidoPropertyChange
        cleanPanel();
    }//GEN-LAST:event_tfApellidoPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbPanelApellido;
    private javax.swing.JLabel lbPanelDni;
    private javax.swing.JLabel lbPanelId;
    private javax.swing.JLabel lbPanelNombre;
    private javax.swing.JTable tbEncontrados;
    private javax.swing.JTextField tfApellido;
    // End of variables declaration//GEN-END:variables

    public void cabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        tbEncontrados.setModel(modelo);
    }

    public void centrarEnDesktopPane() {
        Dimension desktopSize = this.getDesktopPane().getSize();
        Dimension internalFrameSize = this.getSize();
        int x = (desktopSize.width - internalFrameSize.width) / 2;
        int y = (desktopSize.height - internalFrameSize.height) / 2;
        this.setLocation(x, y);
    }

    public void cleanPanel() {
        lbPanelId.setText("*********");
        lbPanelDni.setText("*********");
        lbPanelApellido.setText("*********");
        lbPanelNombre.setText("*********");
    }
}
