package vistas;

import accesoADatos.AlumnoData;
import accesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Materia;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andres
 */
public class BajasView extends javax.swing.JInternalFrame {

    AlumnoData alumnoData = new AlumnoData();
    MateriaData materiaData = new MateriaData();
    DefaultTableModel modelA = new DefaultTableModel();
    DefaultTableModel modelM = new DefaultTableModel();

    public BajasView() {
        initComponents();
        setSize(586, 524);
        cabeceraTablaAlumnos();
        cabeceraTablaMateria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnAlumnos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfApellidoAlumno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAlumno = new javax.swing.JTable();
        pnMaterias = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNombreMateria = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMaterias = new javax.swing.JTable();
        btActivarAlumno = new javax.swing.JButton();
        btActivarMateria = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(39, 60, 117));
        jPanel1.setForeground(new java.awt.Color(39, 60, 117));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado de Alumnos || Materias de Baja");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 550, 24);

        pnAlumnos.setBackground(new java.awt.Color(0, 102, 255));
        pnAlumnos.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");

        tfApellidoAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfApellidoAlumnoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidoAlumnoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Alumnos");

        tbAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbAlumno);

        javax.swing.GroupLayout pnAlumnosLayout = new javax.swing.GroupLayout(pnAlumnos);
        pnAlumnos.setLayout(pnAlumnosLayout);
        pnAlumnosLayout.setHorizontalGroup(
            pnAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnAlumnosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfApellidoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                .addGap(8, 8, 8))
        );
        pnAlumnosLayout.setVerticalGroup(
            pnAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlumnosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(pnAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(pnAlumnos);
        pnAlumnos.setBounds(10, 90, 270, 290);

        pnMaterias.setBackground(new java.awt.Color(0, 153, 153));
        pnMaterias.setMinimumSize(new java.awt.Dimension(260, 290));
        pnMaterias.setPreferredSize(new java.awt.Dimension(260, 290));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Materias");

        tfNombreMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNombreMateriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreMateriaKeyTyped(evt);
            }
        });

        tbMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbMaterias);

        javax.swing.GroupLayout pnMateriasLayout = new javax.swing.GroupLayout(pnMaterias);
        pnMaterias.setLayout(pnMateriasLayout);
        pnMateriasLayout.setHorizontalGroup(
            pnMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnMateriasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombreMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnMateriasLayout.setVerticalGroup(
            pnMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pnMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(pnMaterias);
        pnMaterias.setBounds(290, 90, 270, 290);

        btActivarAlumno.setBackground(new java.awt.Color(39, 60, 117));
        btActivarAlumno.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btActivarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btActivarAlumno.setText("Activar Alumno");
        btActivarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActivarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btActivarAlumno);
        btActivarAlumno.setBounds(60, 410, 160, 28);

        btActivarMateria.setBackground(new java.awt.Color(39, 60, 117));
        btActivarMateria.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btActivarMateria.setForeground(new java.awt.Color(255, 255, 255));
        btActivarMateria.setText("Activar Materia");
        btActivarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActivarMateriaActionPerformed(evt);
            }
        });
        jPanel1.add(btActivarMateria);
        btActivarMateria.setBounds(340, 410, 160, 28);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 50, 550, 3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfApellidoAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoAlumnoKeyReleased
        List<Alumno> listaAlumno = alumnoData.listaAlumnosBaja(tfApellidoAlumno.getText());
        modelA.setRowCount(0);
        if (listaAlumno != null) {
            for (Alumno alumno : listaAlumno) {
                modelA.addRow(new Object[]{alumno.getIdAlumno(), alumno.getApellido(), alumno.getNombre()});
            }
        }
    }//GEN-LAST:event_tfApellidoAlumnoKeyReleased

    private void tfNombreMateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreMateriaKeyReleased
        List<Materia> listaMateriasBajas = materiaData.listaMateriasBaja(tfNombreMateria.getText());
        modelM.setRowCount(0);
        if (listaMateriasBajas != null) {
            for (Materia materia : listaMateriasBajas) {
                modelM.addRow(new Object[]{materia.getIdMateria(), materia.getNombre(), materia.getAnioMateria()});
            }
        }
    }//GEN-LAST:event_tfNombreMateriaKeyReleased

    private void tfApellidoAlumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoAlumnoKeyTyped
        AccesoService.Service.esLetra(evt);
    }//GEN-LAST:event_tfApellidoAlumnoKeyTyped

    private void btActivarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActivarAlumnoActionPerformed
        int selectedRow = tbAlumno.getSelectedRow();
        if (selectedRow >= 0) {
            int idAlumno = (int) tbAlumno.getValueAt(selectedRow, 0);
            alumnoData.activarAlumno(idAlumno);
            cleanAlumno();
        } else {
            JOptionPane.showMessageDialog(null, "No hay alumno seleccionado.");
        }
    }//GEN-LAST:event_btActivarAlumnoActionPerformed

    private void tfNombreMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreMateriaKeyTyped
        AccesoService.Service.esLetra(evt);
    }//GEN-LAST:event_tfNombreMateriaKeyTyped

    private void btActivarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActivarMateriaActionPerformed
    int selectedRow=tbMaterias.getSelectedRow();
        if (selectedRow>=0) {
            int idMateria=(int)tbMaterias.getValueAt(selectedRow, 0);
            materiaData.activarMateria(idMateria);
            cleanMateria();
        }else{
            JOptionPane.showMessageDialog(null, "No hay materia seleccionado");
        }
    }//GEN-LAST:event_btActivarMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActivarAlumno;
    private javax.swing.JButton btActivarMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnAlumnos;
    private javax.swing.JPanel pnMaterias;
    private javax.swing.JTable tbAlumno;
    private javax.swing.JTable tbMaterias;
    private javax.swing.JTextField tfApellidoAlumno;
    private javax.swing.JTextField tfNombreMateria;
    // End of variables declaration//GEN-END:variables

    public void cabeceraTablaAlumnos() {
        modelA.addColumn("ID");
        modelA.addColumn("Nombre");
        modelA.addColumn("Apellido");
        tbAlumno.setModel(modelA);
    }

    private void cabeceraTablaMateria() {
        modelM.addColumn("ID");
        modelM.addColumn("Nombre");
        modelM.addColumn("Año");
        tbMaterias.setModel(modelM);
    }

    public void centrarEnDesktopPane() {
        Dimension desktopSize = this.getDesktopPane().getSize();
        Dimension internalFrameSize = this.getSize();
        int x = (desktopSize.width - internalFrameSize.width) / 2;
        int y = (desktopSize.height - internalFrameSize.height) / 2;
        this.setLocation(x, y);
    }
    
    private void cleanMateria(){
        tfNombreMateria.setText("");
        modelM.setRowCount(0);
    }
    
    private void cleanAlumno(){
        tfApellidoAlumno.setText("");
        modelA.setRowCount(0);
    }

}
