/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import accesoADatos.AlumnoData;
import accesoADatos.InscripcionData;
import accesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;


/**
 *
 * @author telma
 */
public class NotaView extends javax.swing.JInternalFrame {
AlumnoData alumnoData=new AlumnoData();
DefaultTableModel modelo=new DefaultTableModel();
InscripcionData inscripcionData=new InscripcionData();
MateriaData materiaData=new MateriaData(); 

    public NotaView() {
        initComponents();
        cargarCombo();
        armarCabecera();
        cargarInscripcion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbListadoAlumnos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNotas = new javax.swing.JTable();
        bGuardar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        jLabel1.setText("Seleccione un Alumno");

        jLabel2.setText("     Carga de Datos");

        cbListadoAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListadoAlumnosActionPerformed(evt);
            }
        });

        tbNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbNotas);

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbListadoAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbListadoAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bSalir))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbListadoAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListadoAlumnosActionPerformed
      cargarInscripcion();  
    }//GEN-LAST:event_cbListadoAlumnosActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        int filaSeleccionada = tbNotas.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idAlumno = ((Alumno) cbListadoAlumnos.getSelectedItem()).getIdAlumno();
            int idMateria = (int) tbNotas.getValueAt(filaSeleccionada, 0);
            try {
                String notaString = (String) tbNotas.getValueAt(filaSeleccionada, 2);
                double nuevaNota = Double.parseDouble(notaString);
                if (nuevaNota > 0 && nuevaNota <= 10) {
                    inscripcionData.actualizarNota(idAlumno, idMateria, nuevaNota);

                } else {
                    JOptionPane.showMessageDialog(null, "Notas validas: entre 1 y 10.");
                }
            } catch (ClassCastException e) {
                JOptionPane.showMessageDialog(null, "Debe ingresar nota y presionar Enter \n" + e.getMessage());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Ingrese una nota valida.");
            }

            limpiarTabla();
            cargarInscripcion(); // Actualizar la tabla después de modificar...
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una materia para actualizar la nota.");
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<Alumno> cbListadoAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNotas;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        List<Alumno> listaAlumnos = new ArrayList<>();
        listaAlumnos=alumnoData.listarAlumnos();
        Collections.sort(listaAlumnos);
        if(listaAlumnos!=null){
        for (Alumno alumno : listaAlumnos) {
                cbListadoAlumnos.addItem(alumno);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay alumnos para agregar");
        }
    }

    private void armarCabecera() {
        modelo.addColumn("codigo");
        modelo.addColumn("nombre");
        modelo.addColumn("nota");
        tbNotas.setModel(modelo);
        
    }

    private void cargarInscripcion() {
        limpiarTabla();
        Alumno alumno=(Alumno) cbListadoAlumnos.getSelectedItem();
        if(alumno!=null){
            List<Inscripcion> inscripciones=inscripcionData.obtenerInscripcionesPorAlumno(alumno.getIdAlumno());
            for (Inscripcion inscripcion : inscripciones) {
                Materia materia=materiaData.buscarMateria(inscripcion.getMateria().getIdMateria());
                modelo.addRow(new Object[]{materia.getIdMateria(), materia.getNombre(), inscripcion.getNota()});
                
            }
        }
    }
    
    private void limpiarTabla(){
        modelo.setRowCount(0);
    }
    


}

